#*******************************************************************************
# Copyright (c) 2017 Red Hat, Eurotech, Inc and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Red Hat, Inc. - initial implementation
#     Eurotech - initial implementation of Kapua components
#
#******************************************************************************
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Red Hat IoT Demo Application Template
    iconClass: icon-shadowman
    tags: jboss,iot,kapua,kura,eclipse
  name: iot-demo

parameters:
- name: IMAGE_VERSION
  description: The version of the image to use
  value: latest
- name: DOCKER_ACCOUNT
  description: The docker hub account name to pull from
  value: redhatiot
- name: JOLOKIA_PASSWORD
  description: The password used for the Jolokia endpoint authentication
  generate: expression
  from: '[a-zA-Z0-9]{15}'
  required: true
- name: JOLOKIA_USER
  description: The username used for the Jolokia endpoint authentication
  value: jolokia
- name: ELASTIC_SEARCH_MEMORY
  descrption: The minimum and maximun Java heap space for Elasticsearch
  value: 256m
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/content/groups/public/)
  displayName: Maven mirror url
  name: MAVEN_MIRROR_URL
  required: false
- description: MQ cluster password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: MQ_CLUSTER_PASSWORD
  required: true
- description: JGroups cluster password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
- description: Git source URI for application
  name: GIT_URI
  required: true
  value: https://github.com/redhat-iot/summit2017
- description: Git branch/tag reference
  name: GIT_REF
  value: master
- description: MQ Broker username
  name: BROKER_USERNAME
  value: "demo-gw2"
  required: true
- description: MQ Broker password
  name: BROKER_PASSWORD
  value: "RedHat123"
  required: true
- description: OpenShift load-balanced MQ Broker service name
  name: BROKER_WS_NAME
  value: "broker"
  required: true

labels:
  demo: cloudera
  app: kapua

objects:

# Config Maps (Hawkular)

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawkular-openshift-agent-kapua
    labels:
      name: hawkular-openshift-agent-kapua
      hawkular-openshift-agent: jolokia-kapua
  data:
    hawkular-openshift-agent: |
      endpoints:
      - type: jolokia
        protocol: https
        port: 8778
        path: /jolokia/
        collection_interval: 15s
        credentials:
          username: ${JOLOKIA_USER}
          password: ${JOLOKIA_PASSWORD}
        tls:
          skip_certificate_validation: true
        metrics:
        - name: java.lang:type=Memory#HeapMemoryUsage#used
          id: java_memory_heap_used
          type: gauge
          description: Heap Memory Used
          units: B

# Deployment configs

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: sql
    name: sql
  spec:
    replicas: 1
    selector:
      app: sql
      deploymentconfig: sql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sql
          deploymentconfig: sql
          hawkular-openshift-agent: jolokia-kapua
      spec:
        containers:
        - env:
          - name: H2_OPTS
            value: -javaagent:/jolokia-jvm-agent.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false,user=${JOLOKIA_USER},password=${JOLOKIA_PASSWORD}
          image: ${DOCKER_ACCOUNT}/kapua-sql:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: sql
          ports:
          - containerPort: 8778 
            name: jolokia
          - containerPort: 3306
            protocol: TCP
          - containerPort: 8181
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /opt/h2-data
            name: sql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: sql-data
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-kapua

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: kapua-broker
    name: kapua-broker
  spec:
    replicas: 1
    selector:
      app: kapua-broker
      deploymentconfig: kapua-broker
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/container.kapua-broker.image.entrypoint: '["/maven/bin/activemq","console"]'
        labels:
          app: kapua-broker
          deploymentconfig: kapua-broker
          hawkular-openshift-agent: jolokia-kapua
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_OPTS
            value: -Dcommons.db.connection.host=$SQL_SERVICE_HOST -Dcommons.db.connection.port=$SQL_PORT_3306_TCP_PORT -Ddatastore.elasticsearch.nodes=$ELASTICSEARCH_PORT_9200_TCP_ADDR -javaagent:/jolokia-jvm-agent.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false,user=${JOLOKIA_USER},password=${JOLOKIA_PASSWORD}
          image: ${DOCKER_ACCOUNT}/kapua-broker:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: kapua-broker
          ports:
          - containerPort: 8778 
            name: jolokia
          - containerPort: 1883
            protocol: TCP
          - containerPort: 61614
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /maven/data
            name: kapua-broker-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: kapua-broker-volume-1

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: kapua-console
    name: kapua-console
  spec:
    replicas: 1
    selector:
      app: kapua-console
      deploymentconfig: kapua-console
    template:
      metadata:
        labels:
          app: kapua-console
          deploymentconfig: kapua-console
          hawkular-openshift-agent: jolokia-kapua
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -Ddatastore.elasticsearch.nodes=$ELASTICSEARCH_PORT_9200_TCP_ADDR -Dcommons.db.connection.host=$SQL_SERVICE_HOST -Dcommons.db.connection.port=$SQL_PORT_3306_TCP_PORT -Dbroker.host=$KAPUA_BROKER_SERVICE_HOST -javaagent:/jolokia-jvm-agent.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false,user=${JOLOKIA_USER},password=${JOLOKIA_PASSWORD}
          image: ${DOCKER_ACCOUNT}/kapua-console-jetty:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: kapua-console
          ports:
          - containerPort: 8778 
            name: jolokia
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-kapua

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: kapua-api
      hawkular-openshift-agent: jolokia-kapua
    name: kapua-api
  spec:
    replicas: 1
    selector:
      app: kapua-api
      deploymentconfig: kapua-api
    template:
      metadata:
        labels:
          app: kapua-api
          deploymentconfig: kapua-api
          hawkular-openshift-agent: jolokia-kapua
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -Ddatastore.elasticsearch.nodes=$ELASTICSEARCH_PORT_9200_TCP_ADDR -Dcommons.db.connection.host=$SQL_SERVICE_HOST -Dcommons.db.connection.port=$SQL_PORT_3306_TCP_PORT -Dbroker.host=$KAPUA_BROKER_SERVICE_HOST -javaagent:/jolokia-jvm-agent.jar=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false,user=${JOLOKIA_USER},password=${JOLOKIA_PASSWORD}
          image: ${DOCKER_ACCOUNT}/kapua-api-jetty:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: kapua-console
          ports:
          - containerPort: 8778 
            name: jolokia
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-kapua

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: elasticsearch
      hawkular-openshift-agent: jolokia-kapua
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      app: elasticsearch
      deploymentconfig: elasticsearch
    template:
      metadata:
        labels:
          app: elasticsearch
          deploymentconfig: elasticsearch
          hawkular-openshift-agent: jolokia-kapua
      spec:
        containers:
        - env:
          - name: ES_HEAP_SIZE
            value: ${ELASTIC_SEARCH_MEMORY}
          - name: ES_JAVA_OPTS
            value: -Des.cluster.name=kapua-datastore -Des.http.cors.enabled=true -Des.http.cors.allow-origin=*
          image: elasticsearch:2.4
          imagePullPolicy: Always
          name: elasticsearch
          ports:
          - containerPort: 9200
          - containerPort: 9300
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-kapua
        - name: elasticsearch-data
          emptyDir: {}

# Services
        
- apiVersion: v1
  kind: Service
  metadata:
    name: sql
    labels:
      app: sql
  spec:
    ports:
    - name: h2-sql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: h2-web
      protocol: TCP
      port: 8181
      targetPort: 8181
    selector:
      app: sql
      deploymentconfig: sql
- apiVersion: v1
  kind: Service
  metadata:
    name: kapua-broker
    labels:
      app: kapua-broker
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "sql", "kind": "Service"}, {"name": "elasticsearch", "kind": "Service"}]'
  spec:
    ports:
    - name: mqtt-tcp
      protocol: TCP
      port: 1883
      nodePort: 31883
    - name: mqtts-tcp
      protocol: TCP
      port: 8883
      nodePort: 31885
    - name: mqtt-websocket-tcp
      protocol: TCP
      port: 61614
      nodePort: 31614
    selector:
      app: kapua-broker
      deploymentconfig: kapua-broker
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: kapua-console
    labels:
      app: kapua-console
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "sql", "kind": "Service"}]'
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: kapua-console
      deploymentconfig: kapua-console
- apiVersion: v1
  kind: Service
  metadata:
    name: kapua-api
    labels:
      app: kapua-api
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "sql", "kind": "Service"}]'
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: kapua-api
      deploymentconfig: kapua-api
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    labels:
      app: elasticsearch
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
    selector:
      app: elasticsearch
      deploymentconfig: elasticsearch

# Routes

- apiVersion: v1
  kind: Route
  metadata:
    name: ${BROKER_WS_NAME}
    labels:
      app: kapua-broker
  spec:
    to:
      kind: Service
      name: kapua-broker
    port:
      targetPort: mqtt-websocket-tcp
- apiVersion: v1
  kind: Route
  metadata:
    name: console
    labels:
      app: kapua-console
  spec:
    to:
      kind: Service
      name: kapua-console
    port:
      targetPort: http
- apiVersion: v1
  kind: Route
  metadata:
    name: api
    labels:
      app: kapua-api
  spec:
    to:
      kind: Service
      name: kapua-api
    port:
      targetPort: http
- apiVersion: v1
  kind: Route
  metadata:
    name: search
    labels:
      app: elasticsearch
  spec:
    to:
      kind: Service
      name: elasticsearch
    port:
      targetPort: http

###
### END OpenShift Template items from Kapua dev-tools
###
